# Site settings
title: Kabir Goel
email: kabirgoel.kg@gmail.com
description: >
  I'm a 14 year old programmer, Unix geek and quizzer from New Delhi, India.
baseurl: ""
url: "http://kabirgoel.com" # the base hostname & protocol for your site
twitter_username: notkabir
github_username: kbrgl
instagram_username: kabir_goel
spotify: 12181834510
email: kabirgoel.kg@gmail.com
# Build settings
markdown: kramdown
