# Site settings
title: Kabir's Blog
description: >
  The thoughts and ramblings of a 13 year old.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbrgl.github.io/" # the base hostname & protocol for your site
twitter_username: notkabir
github_username:  kbrgl

# Build settings
markdown: kramdown
