# Site settings
title: Kabir Goel
description: >
  This is where I write about technology and more.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kbrgl.github.io/" # the base hostname & protocol for your site
twitter_username: notkabir
github_username:  kbrgl

# Build settings
markdown: kramdown
