# Site settings
title: Kabir Goel
email: kabirgoel.kg@gmail.com
description: >
  Hey there! I'm Kabir, a computer ninja and aspiring quizzer.
baseurl: ""
url: "http://kabirgoel.com" # the base hostname & protocol for your site
twitter_username: notkabir
github_username: kbrgl
spotify: 12181834510
medium_username: kbrgl
email: kabirgoel.kg@gmail.com
# Build settings
markdown: kramdown
