# Site settings
title: Kabir Goel
email: kabirgoel.kg@gmail.com
description: >
  programmer. that's about it.
baseurl: ""
url: "http://kabirgoel.com" # the base hostname & protocol for your site
twitter_username: notkabir
github_username:  kbrgl

# Build settings
markdown: kramdown
